import type {
  Patient,
  Invoice,
  Partner,
  RevenueSnapshot,
  StageMeta,
  PipelineStage,
} from "./types";

/* ─── Stage metadata ─── */
export const STAGE_META: Record<PipelineStage, StageMeta> = {
  inquiry: {
    key: "inquiry",
    label: "Inquiry",
    color: "#4A90A4",
    bgTint: "rgba(74,144,164,0.08)",
  },
  coordination: {
    key: "coordination",
    label: "Coordination",
    color: "#7B6FA0",
    bgTint: "rgba(123,111,160,0.08)",
  },
  treatment: {
    key: "treatment",
    label: "Treatment",
    color: "#0B4042",
    bgTint: "rgba(11,64,66,0.08)",
  },
  recovery: {
    key: "recovery",
    label: "Recovery",
    color: "#3D8B6E",
    bgTint: "rgba(61,139,110,0.08)",
  },
  billing: {
    key: "billing",
    label: "Billing",
    color: "#B8903A",
    bgTint: "rgba(184,144,58,0.08)",
  },
};

/* ─── Patients ─── */
export const patients: Patient[] = [
  {
    id: "PAT-001",
    name: "Aissatou Diallo",
    country: "Guinea",
    countryFlag: "\u{1F1EC}\u{1F1F3}",
    summary: "Cardiac valve replacement — referred by Dr. Kouyat\u{00E9}",
    stage: "inquiry",
    nextDate: "Apr 6",
    assignedTo: "Fatima B.",
    valueMad: 185_000,
    notes:
      "Initial call received via WhatsApp. Patient is 54, has a history of rheumatic heart disease. Awaiting medical records from Conakry hospital.",
  },
  {
    id: "PAT-002",
    name: "Moussa Traor\u{00E9}",
    country: "Mali",
    countryFlag: "\u{1F1F2}\u{1F1F1}",
    summary: "Urgent neurosurgery consultation — spinal compression",
    stage: "inquiry",
    nextDate: "Apr 5",
    assignedTo: "Driss K.",
    valueMad: 240_000,
    notes:
      "Referred by partner clinic in Bamako. MRI scans being transferred digitally. Patient experiencing progressive numbness in lower limbs.",
  },
  {
    id: "PAT-003",
    name: "Amina Ouedraogo",
    country: "Burkina Faso",
    countryFlag: "\u{1F1E7}\u{1F1EB}",
    summary: "Knee replacement surgery — bilateral",
    stage: "coordination",
    nextDate: "Apr 8",
    assignedTo: "Fatima B.",
    valueMad: 142_000,
    notes:
      "Medical records validated. Coordinating with Clinique Al-Hayat for surgical dates. Patient needs hotel booking for 3-week stay with companion.",
  },
  {
    id: "PAT-004",
    name: "Ibrahim Ndiaye",
    country: "Senegal",
    countryFlag: "\u{1F1F8}\u{1F1F3}",
    summary: "Oncology treatment plan — liver tumor staging",
    stage: "coordination",
    nextDate: "Apr 7",
    assignedTo: "Driss K.",
    valueMad: 310_000,
    notes:
      "Biopsy results received from Dakar. Dr. Benali reviewing the case. Need to coordinate PET scan and oncology board review before treatment plan.",
  },
  {
    id: "PAT-005",
    name: "Fatoumata Camara",
    country: "Guinea",
    countryFlag: "\u{1F1EC}\u{1F1F3}",
    summary: "Pediatric cardiac surgery — tetralogy of Fallot",
    stage: "treatment",
    nextDate: "Apr 4",
    assignedTo: "Fatima B.",
    valueMad: 275_000,
    notes:
      "Surgery scheduled for tomorrow at Clinique Al-Hayat. Dr. Marrakchi operating. Mother staying at Riad Salam. Airport transfer confirmed for post-op return.",
  },
  {
    id: "PAT-006",
    name: "Ousmane Kon\u{00E9}",
    country: "C\u{00F4}te d'Ivoire",
    countryFlag: "\u{1F1E8}\u{1F1EE}",
    summary: "Orthopedic revision — hip prosthesis replacement",
    stage: "treatment",
    nextDate: "Apr 5",
    assignedTo: "Driss K.",
    valueMad: 198_000,
    notes:
      "Currently admitted at Clinique R\u{00E9}sidence. Surgery completed yesterday, recovering well. Physiotherapy begins tomorrow. Driver on standby for daily transport.",
  },
  {
    id: "PAT-007",
    name: "Mariama Ba",
    country: "Senegal",
    countryFlag: "\u{1F1F8}\u{1F1F3}",
    summary: "Post-operative recovery — spinal fusion",
    stage: "recovery",
    nextDate: "Apr 10",
    assignedTo: "Fatima B.",
    valueMad: 220_000,
    notes:
      "Surgery was successful. Patient doing daily physiotherapy. Walking with assistance. Follow-up MRI scheduled for Apr 10. Flight home tentatively Apr 14.",
  },
  {
    id: "PAT-008",
    name: "Cheikh Sow",
    country: "Mauritania",
    countryFlag: "\u{1F1F2}\u{1F1F7}",
    summary: "Recovery monitoring — post cardiac catheterization",
    stage: "recovery",
    nextDate: "Apr 6",
    assignedTo: "Driss K.",
    valueMad: 95_000,
    notes:
      "Procedure went smoothly. Patient resting at hotel with daily nurse visits. Cleared for travel in 48 hours pending final bloodwork.",
  },
  {
    id: "PAT-009",
    name: "Kadiatou Bah",
    country: "Guinea",
    countryFlag: "\u{1F1EC}\u{1F1F3}",
    summary: "Completed — ophthalmology surgery, bilateral cataracts",
    stage: "billing",
    nextDate: "Apr 3",
    assignedTo: "Fatima B.",
    valueMad: 68_000,
    notes:
      "Treatment fully completed. Patient returned home safely. Final invoice sent, partial payment received. Awaiting remaining balance from family.",
  },
  {
    id: "PAT-010",
    name: "Amadou Diarra",
    country: "Mali",
    countryFlag: "\u{1F1F2}\u{1F1F1}",
    summary: "Completed — kidney stone lithotripsy",
    stage: "billing",
    nextDate: "Apr 2",
    assignedTo: "Driss K.",
    valueMad: 52_000,
    notes:
      "All services rendered and confirmed. Patient flew home Mar 30. Invoice fully paid. Commission to Clinique R\u{00E9}sidence pending.",
  },
];

/* ─── Invoices ─── */
export const invoices: Invoice[] = [
  {
    id: "INV-2401",
    patientId: "PAT-009",
    patientName: "Kadiatou Bah",
    description: "Ophthalmology — bilateral cataract surgery",
    amountMad: 68_000,
    status: "pending",
    date: "Apr 1",
  },
  {
    id: "INV-2402",
    patientId: "PAT-010",
    patientName: "Amadou Diarra",
    description: "Urology — kidney stone lithotripsy",
    amountMad: 52_000,
    status: "paid",
    date: "Mar 28",
  },
  {
    id: "INV-2403",
    patientId: "PAT-005",
    patientName: "Fatoumata Camara",
    description: "Cardiac — pediatric tetralogy repair (deposit)",
    amountMad: 137_500,
    status: "paid",
    date: "Mar 25",
  },
  {
    id: "INV-2404",
    patientId: "PAT-006",
    patientName: "Ousmane Kon\u{00E9}",
    description: "Orthopedics — hip prosthesis + hospital stay",
    amountMad: 198_000,
    status: "pending",
    date: "Apr 2",
  },
  {
    id: "INV-2405",
    patientId: "PAT-007",
    patientName: "Mariama Ba",
    description: "Neurosurgery — spinal fusion + rehab",
    amountMad: 220_000,
    status: "pending",
    date: "Mar 30",
  },
  {
    id: "INV-2406",
    patientId: "PAT-008",
    patientName: "Cheikh Sow",
    description: "Cardiology — catheterization + monitoring",
    amountMad: 95_000,
    status: "paid",
    date: "Mar 27",
  },
  {
    id: "INV-2390",
    patientId: "PAT-003",
    patientName: "Amina Ouedraogo",
    description: "Orthopedics — consultation deposit",
    amountMad: 35_000,
    status: "overdue",
    date: "Mar 15",
  },
];

/* ─── Partners ─── */
export const partners: Partner[] = [
  {
    id: "PART-01",
    name: "Clinique Al-Hayat",
    type: "clinic",
    city: "Casablanca",
    status: "active",
    activeCases: 3,
    contact: "+212 522 36 78 00",
    rating: "4.9",
  },
  {
    id: "PART-02",
    name: "Clinique R\u{00E9}sidence",
    type: "clinic",
    city: "Rabat",
    status: "active",
    activeCases: 2,
    contact: "+212 537 67 22 00",
    rating: "4.7",
  },
  {
    id: "PART-03",
    name: "Dr. Benali Youssef",
    type: "doctor",
    city: "Casablanca",
    status: "active",
    activeCases: 2,
    contact: "+212 661 44 55 66",
    rating: "4.9",
  },
  {
    id: "PART-04",
    name: "Dr. Marrakchi Hassan",
    type: "doctor",
    city: "Casablanca",
    status: "active",
    activeCases: 1,
    contact: "+212 662 33 77 88",
    rating: "4.8",
  },
  {
    id: "PART-05",
    name: "Riad Salam Guest House",
    type: "hotel",
    city: "Casablanca",
    status: "active",
    activeCases: 2,
    contact: "+212 522 29 13 00",
    rating: "4.6",
  },
  {
    id: "PART-06",
    name: "Atlas Comfort Suites",
    type: "hotel",
    city: "Rabat",
    status: "review",
    activeCases: 1,
    contact: "+212 537 77 88 99",
    rating: "4.3",
  },
  {
    id: "PART-07",
    name: "MedTransfer Morocco",
    type: "transport",
    city: "Casablanca",
    status: "active",
    activeCases: 4,
    contact: "+212 660 11 22 33",
    rating: "4.5",
  },
  {
    id: "PART-08",
    name: "SafeRide Medical",
    type: "transport",
    city: "Rabat",
    status: "inactive",
    activeCases: 0,
    contact: "+212 661 99 88 77",
    rating: "3.9",
  },
];

/* ─── Revenue snapshots (pre-aggregated) ─── */
export const revenueSnapshots: Record<string, RevenueSnapshot> = {
  daily: {
    period: "daily",
    revenue: 48_500,
    expenses: 12_200,
    profit: 36_300,
    invoiceCount: 2,
  },
  weekly: {
    period: "weekly",
    revenue: 342_000,
    expenses: 89_500,
    profit: 252_500,
    invoiceCount: 7,
  },
  monthly: {
    period: "monthly",
    revenue: 1_285_000,
    expenses: 341_000,
    profit: 944_000,
    invoiceCount: 24,
  },
  yearly: {
    period: "yearly",
    revenue: 14_620_000,
    expenses: 3_890_000,
    profit: 10_730_000,
    invoiceCount: 287,
  },
};
